crm/urls.py
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from leads.views import home_page,HomePageView,SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePageView.as_view(),name='home-page'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('leads/' ,include('leads.urls',namespace='leads')),
    path('agents/' ,include('agents.urls',namespace='agents')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import lead_list,lead_detail,lead_create,lead_update,lead_delete,LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView
app_name="leads"
urlpatterns = [
    path('',LeadListView.as_view(),name='lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(),name='lead-detail'),
    path('create/',LeadCreateView.as_view(),name='lead-create'),
    path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead-update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(),name='lead-delete'),
   
    
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
# pre_save called before something is committed to the DB
# post_save sa called after data is commited to the DB
# listens to when a user is commited to the db
# signals are events that are fired when certain actions take place

# Create your models here.
class User(AbstractUser):
    pass
class UserProfile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    SOURCE_CHOICES={
        ("Youtube","Youtube"),
        ("Whatsapp","Whatsapp"),
        ("Facebook","Facebook"),
    }
    first_name=models.CharField(max_length=50)
    last_name=models.CharField( max_length=50)
    age=models.IntegerField(default=0)
    phoned=models.BooleanField(default=False)
    source=models.CharField(choices=SOURCE_CHOICES, max_length=100)
    profile_picture=models.ImageField(null=True, blank=True)
    special_file=models.FileField(null=True,blank=True)
    agent=models.ForeignKey("Agent", on_delete=models.SET_NULL,null=True)
   
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    
class Agent(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    organization=models.ForeignKey("UserProfile",on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username



def post_user_created_signal(sender,instance,created,**kwargs):
    # sender-
    # instance-actual model that was saved
    # created argument tells us where or not this was the moment the model instance was created
    # kwargs captures the rest of the arguments if there are any
    if created:
        UserProfile.objects.create(user=instance)
    print(instance,created)

post_save.connect(post_user_created_signal,sender=User)
# connect takes in the function we want to call and the sender(the model that is sending the event)

   

    

leads/forms.py
from django import forms
from .models import Lead,User
from django.contrib.auth.forms import UserCreationForm,UsernameField

class CustomUserForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class LeadModelForm(forms.ModelForm):
    
    class Meta:
        model = Lead
        fields = ("first_name",
                "last_name",
                "age",
                "source",
                "agent"
                 )

class LeadForm(forms.Form):
    first_name=forms.CharField(max_length=50)
    last_name=forms.CharField(max_length=50)
    age=forms.IntegerField(min_value=0)

leads/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from .models import Lead,Agent
from .forms import LeadForm,LeadModelForm,CustomUserForm
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,TemplateView,DetailView,CreateView,UpdateView,DeleteView
# Create your views here.

# In programming, a mixin is a class that provides functionality to be inherited, but isn’t meant for  instantiation on its own. 
#In programming languages with multiple inheritance, mixins can be used to add enhanced functionality and behavior to classes.
# We can use the power of mixins to compose our own view classes for our Django apps.
# When using mixins to compose our own view classes, we recommend these rules of inheritance provided by Kenneth Love.
#  Ļe rules follow Python’s method resolution order, which in the most
# simplistic deŀnition possible, proceeds from left to right:
# .
# 1 Ļe base view classes provided by Django always go to the right.
# .
# 2 Mixins go to the left of the base view.
# .
# 3 Mixins should inherit from Python’s built-in object type.

class SignUpView(CreateView):
    template_name="registration/signup.html"
    form_class=CustomUserForm

    def get_success_url(self):
        return reverse("login")


class HomePageView(TemplateView):
    template_name="home_page.html"

class LeadListView(LoginRequiredMixin,ListView):
    queryset=Lead.objects.all()
    context_object_name="leads"
    template_name = 'leads/lead_list.html'
class LeadDetailView(LoginRequiredMixin,DetailView):
    queryset=Lead.objects.all()
    context_object_name="lead"
    template_name="leads/lead_detail.html"

class LeadCreateView(LoginRequiredMixin,CreateView):
    template_name="leads/create_lead.html"
    form_class=LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")



class LeadUpdateView(LoginRequiredMixin,UpdateView):
    template_name="leads/update_lead.html"
    form_class=LeadModelForm
    queryset=Lead.objects.all()
class LeadDeleteView(DeleteView):
    template_name="leads/delete_lead.html"
    queryset=Lead.objects.all()
    def get_success_url(self):
        return reverse("leads:lead-list")




def home_page(request):
    return render(request,"home_page.html")



def lead_list(request):
    leads=Lead.objects.all()
    context={
       
       "leads":leads
    }
    return render(request,"leads/lead_list.html",context)



def lead_detail(request,pk):
    
    lead=Lead.objects.get(id=pk)
    print(lead)
    context={
        "lead":lead
    }
    return render(request,"leads/lead_detail.html",context)

def lead_create(request):
    
    form=LeadModelForm()
    if request.method =="POST":
        print("Receiving a post request")
        form=LeadModelForm(request.POST)
        if form.is_valid():
            print("Form is valid")
            print(form.cleaned_data)
            
            form.save()
            messages.success(request, 'Lead has been  created!')
            # return redirect("/leads/")

        
    context={
        "form":form
    }

    return render(request,"leads/create_lead.html",context)
def lead_update(request,pk):
    lead=Lead.objects.get(id=pk)
    form=LeadModelForm(instance=lead)
    if request.method =="POST":
        print("Receiving a post request")
        form=LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            print("Form is valid")
            print(form.cleaned_data)
            
            form.save()
            messages.success(request, 'Lead has been  updated!')
            # return redirect("/leads/")
    context={
         "form":form,
         "lead":lead
     }
    return render(request,"leads/update_lead.html",context)
def lead_delete(request,pk):
    lead=Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads/")
# def lead_update(request,pk):
#     lead=Lead.objects.get(id=pk)
#     form=LeadForm()
#     if request.method== "POST":
#         form=LeadForm(request.POST)
#         if form.is_valid():

#             first_name=form.cleaned_data['first_name']
#             last_name=form.cleaned_data['last_name']
#             age=form.cleaned_data['age']

#             lead.first_name=first_name
#             lead.last_name=last_name
#             lead.age=age
#             lead.save()
#             messages.success(request,"Lead has been updated!")
#             return redirect("/leads/")


#     context={
#         "form":form,
#         "lead":lead
#     }
#     return render(request,"leads/update_lead.html",context)

leads/templates/leads/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %} ">
    </head>
    {% include './navbar.html' %}
    <body>
    <div clas="max-w-4xl mx-auto bg-gray-100">
    {% block content %}
   {% include 'scripts.html' %}
   {% endblock content %}
    </div>
    
        
        <script src="" async defer></script>
    </body>
</html>

leads/templates/leads/create_lead.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
  
<div class="card text-center">
  <div class="card-header">
    Create Lead
  </div>
  <div class="card-body">
    <h5 class="card-title">Lead Generation Form</h5>
    <form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-outline-primary">Submit</button>
   </form>
  </div>
  <div class="card-footer text-muted">
   New
  </div>
</div>

        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

leads/templates/leads/delete_lead.html
{% extends './base.html' %}

  {% block content %}

    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
 {{message}}
</div>
  

    {% endfor %}
    {% else %}
 <div>

</div>
{% endif %}
<div class="card text-center">
  <div class="card-header">
    Delete <span style="float:right;"><a href="{% url 'leads:lead-list' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Back To Leads</a></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">Are you sure you want to delete this lead?</h5>
    <form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-outline-primary">Yes</button>
   </form>
  </div>
  <div class="card-footer text-muted">
   New
  </div>
</div>

 {% endblock content %}     

leads/templates/leads/home_page.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
    <div class="card text-center">
  <h5 class="card-header">Open Leads <span style="float:right;"><a href="{% url 'leads:lead-create' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Create a New Lead</a></span>

  <div class="card-body">
    
    <table class="table table-striped">
  <thead>
  
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Age</th>
      <th scope="col">Source</th>
      <th scope="col">Agent</th>
       {% comment %} <th scope="col">Date Created</th> {% endcomment %}
    </tr>
  
  </thead>
  <tbody>
  {% for lead in leads%}
  
    <tr>
  <th scope="row">{{lead.id}}</th>
    
      
      <td>{{lead.first_name}}</td>
      <td>{{lead.last_name}}</td>
      <td>{{lead.age}}</td>
      <td>{{lead.source}}</td>
      <td>{{lead.agent}}<span style="float:right;"><a href="{% url 'leads:lead-detail' lead.pk %}" class="btn btn-outline-info" role="button" aria-pressed="true" >View Lead</a></span></td>
      
    {% endfor %}
    </tr>
    
 
  </tbody>
</table>
 </div>
</div>



        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

leads/templates/leads/lead_detail.html
{% extends "./base.html" %}

{% block content %}
    <div class="card text-center">
  <h5 class="card-header"> Lead{{lead.id}} Details
  <span style="float:right;"><a href="{% url 'leads:lead-list' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Back To Leads</a></span>
  </h5>
  <div class="card-body">
    
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Age</th>
      <th scope="col">Source</th>
      <th scope="col">Agent</th>
    </tr>
  </thead>
  <tbody>

    <tr>
    <th scope="row">{{lead.id}}</th>
    
      
      <td>{{lead.first_name}}</td>
      <td>{{lead.last_name}}</td>
      <td>{{lead.age}}</td>
      <td>{{lead.source}}</td>
      <td>{{lead.agent}}<span style="float:right;"><a href="{% url 'leads:lead-update' lead.pk %}" class="btn btn-outline-info" role="button" aria-pressed="true" >Update Lead</a></span>
      <span style="float:right;margin-right:10px;"><a href="{% url 'leads:lead-delete' lead.pk %}" class="btn btn-outline-danger" role="button" aria-pressed="true" >Delete Lead</a></span>
      </td>
     
    </tr>
  
 
  </tbody>
</table>
 </div>
</div>
 {% endblock content %}

leads/templates/leads/lead_list.html
{% extends "./base.html" %}

{% block content %}
    <div class="card text-center">
  <h5 class="card-header">Open Leads <span style="float:right;"><a href="{% url 'leads:lead-create' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Create a New Lead</a></span>

  <div class="card-body">
    
    <table class="table table-striped">
  <thead>
  
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Age</th>
      <th scope="col">Source</th>
      <th scope="col">Agent</th>
       {% comment %} <th scope="col">Date Created</th> {% endcomment %}
    </tr>
  
  </thead>
  <tbody>
  {% for lead in leads%}
  
    <tr>
  <th scope="row">{{lead.id}}</th>
    
      
      <td>{{lead.first_name}}</td>
      <td>{{lead.last_name}}</td>
      <td>{{lead.age}}</td>
      <td>{{lead.source}}</td>
      <td>{{lead.agent}}<span style="float:right;"><a href="{% url 'leads:lead-detail' lead.pk %}" class="btn btn-outline-info" role="button" aria-pressed="true" >View Lead</a></span></td>
      
    {% endfor %}
    </tr>
    
 
  </tbody>
</table>
 </div>
</div>



   {% endblock content %}

leads/templates/leads/navbar.html
<nav class="navbar navbar-expand-lg  navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'home-page' %}" >DJ CRM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  
       <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'leads:lead-list' %}" >Leads <span class="sr-only">(current)</span></a>
      </li>
      {% if request.user.is_authenticated %}

   <span>
 <li class="nav-item">
      <a class="nav-link">Logged in as : {{request.user.username}}</a>
      </li>
      </span>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}" >Sign In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
      </li>
      {% endif %}
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> {% endcomment %}
    </ul>
  </div>
</nav>

leads/templates/leads/update_lead.html
{% extends './base.html' %}

{% block  content %}
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
 {{message}}
</div>
  

    {% endfor %}
    {% else %}
 <div>

</div>
{% endif %}
<div class="card text-center">
  <div class="card-header">
    Update Lead<span style="float:right;"><a href="{% url 'leads:lead-detail' lead.pk %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Back To Lead {{lead.pk}}</a></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">Lead Update Form</h5>
    <form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-outline-primary">Submit</button>
   </form>
  </div>
  <div class="card-footer text-muted">
   New
  </div>
</div>

   {% endblock content %}   