agents/urls.py
from django.urls import path
from .views import AgentsListView,AgentsCreateView

app_name="agents"
urlpatterns = [
 path('',AgentsListView.as_view(),name="agents-list"),
 path('create/',AgentsCreateView.as_view(),name="agent-create"),
]

crm/urls.py
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from leads.views import home_page,HomePageView,SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePageView.as_view(),name='home-page'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('leads/' ,include('leads.urls',namespace='leads')),
    path('agents/' ,include('agents.urls',namespace='agents')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import lead_list,lead_detail,lead_create,lead_update,lead_delete,LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView
app_name="leads"
urlpatterns = [
    path('',LeadListView.as_view(),name='lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(),name='lead-detail'),
    path('create/',LeadCreateView.as_view(),name='lead-create'),
    path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead-update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(),name='lead-delete'),
   
    
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from leads.models import Agent

from django import forms


class  AgentsModelForm(forms.ModelForm):
    
    class Meta:
        model = Agent
        fields = ("user",)

agents/views.py
from django.shortcuts import render

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentsModelForm


# Create your views here.

class AgentsListView(LoginRequiredMixin,generic.ListView):

    context_object_name='agents'
    template_name="agents/agents_list.html"
    form_class=None

    def get_queryset(self):
        return Agent.objects.all()

class AgentsCreateView(LoginRequiredMixin,generic.CreateView):
    template_name="agents/create_agent.html"
    form_class=AgentsModelForm
    def get_success_url(self):
        return reverse("agents:agent_list.html")


    def form_valid(self,form):
        agent=form.save(commit=False)
        # commit=false means don't commit to the database first
        agent.organization=self.request.user.userprofile
        agent.save()
        return super(AgentsCreateView,self).form_valid(form)




    

agents/templates/agents/agents_list.html
{% extends "leads/base.html" %}

{% block content %}
    <div class="card text-center">
  <h5 class="card-header">All Agents <span style="float:right;"><a href="{% url 'agents:agent-create' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Create a New Agent</a></span>

  <div class="card-body">
    
    <table class="table table-striped">
  <thead>
  
    <tr>
      <th scope="col">#</th>
      <th scope="col">Agent Name</th>
       <th scope="col">Organization</th>
      {% comment %} <th scope="col">Last Name</th>
     
      <th scope="col">Source</th>
      <th scope="col">Agent</th> {% endcomment %}
       {% comment %} <th scope="col">Date Created</th> {% endcomment %}
    </tr>
  
  </thead>
  <tbody>
  {% for agent in agents%}
  
    <tr>
  <th scope="row">{{agent.id}}</th>
    
      
      <td>{{agent.user.username}}</td>
      <td>{{agent.organization}}</td>
      {% comment %} <td>{{lead.last_name}}</td>
      <td>{{lead.age}}</td>
      <td>{{lead.source}}</td>
      <td>{{lead.agent}}<span style="float:right;"><a href="{% url 'leads:lead-detail' lead.pk %}" class="btn btn-outline-info" role="button" aria-pressed="true" >View Lead</a></span></td>
       {% endcomment %}
    {% endfor %}
    </tr>
    
 
  </tbody>
</table>
 </div>
</div>



   {% endblock content %}

agents/templates/agents/create_agent.html
{% extends 'leads/base.html' %}

  {% block content %}

    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
 {{message}}
</div>
  

    {% endfor %}
    {% else %}
 <div>

</div>
{% endif %}
<div class="card text-center">
  <div class="card-header">
    Create <span style="float:right;"><a href="{% url 'agents:agents-list' %}" class="btn btn-outline-primary" role="button" aria-pressed="true" >Back To Agent</a></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">Agent Creation Form</h5>
    <form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-outline-primary">Submit</button>
   </form>
  </div>
  <div class="card-footer text-muted">
   New
  </div>
</div>

 {% endblock content %}     